[package]
name = "statsdproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.23", features = ["derive"] }
crc32fast = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
cadence = { version = "0.29.1", optional = true }

[dev-dependencies]
insta = { version = "1.31.0" }
